// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SortController from "./sort_controller"
import ThemeController from "./theme_controller"
import LangController from "./lang_controller"
import MenuButtonController from "./menu_button_controller"
import CookieBannerController from "./cookie_banner_controller"
import NotificationsErrorsController from "./notifications_errors_controller"
import RepliesController from "./replies_controller"
import ScrollController from "./scroll_controller"

application.register("sort", SortController)
application.register("theme", ThemeController)
application.register("lang", LangController)
application.register("menuButton", MenuButtonController)
application.register("cookieBanner", CookieBannerController)
application.register("notificationsErrors", NotificationsErrorsController)
application.register("replies", RepliesController)
application.register("scroll", ScrollController)
