// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import SortController from "./sort_controller"
import ThemeController from "./theme_controller"
import LangController from "./lang_controller"
import MenuButtonController from "./menu_button_controller"

application.register("hello", HelloController)
application.register("sort", SortController)
application.register("theme", ThemeController)
application.register("lang", LangController)
application.register("menuButton", MenuButtonController)
